# Generated by Django 2.2.3 on 2019-07-31 00:33

from django.db import migrations


def create_data(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task(work_order_number="001", representative_name="Jerry", contact_info="554445454", project_number="01",date="", visit_reason="Repair").save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
    ]



